### ISSUE TITLE
Race condition when waiting repo state

### ISSUE THREAD

**Issue by jvalkeal** [jvalkeal/nexus-sync#4]
During release there was error in logs(thought all worked fine):
```
Staging Repo Release
Released repo test-1078
Waiting repo test-1078 state released
Repo state closed
(node:2840991) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/ghrunner/atest7/_work/_actions/jvalkeal/nexus-sync/gh3-work1/dist/index.js:105:15)
    at settle (/home/ghrunner/atest7/_work/_actions/jvalkeal/nexus-sync/gh3-work1/dist/index.js:6088:12)
    at IncomingMessage.handleStreamEnd (/home/ghrunner/atest7/_work/_actions/jvalkeal/nexus-sync/gh3-work1/dist/index.js:6570:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:2840991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2840991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Post job cleanup.
```
Need to check where it's coming from.

**Comment by jvalkeal** [comment]
Might be when `release-auto-drop` is set to `true`, repo goes away while we're trying to get released state. Probably need to assume in this case that repo release succeed if it's automatically dropped by nexus.
